# nginx-pod.yaml
apiVersion: v1
kind: Pod

metadata:
  name: nginx-server
  labels:
    app: nginx-server

spec:
  initContainers:
    - name: init-nginx-server
      image: nginx
      command: [ 'sh', '-c', 'sleep 2; echo nginx on!' ]

  containers:
    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "0.1"
          memory: "200M"
        limits:
          cpu: "0.5"
          memory: "1G"

      env:
        - name: TESTENV
          value: "testvalue01"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: nginx-server
              resource: requests.cpu
        - name: CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: nginx-server
              resource: limits.cpu
